# Generated by Django 4.2.4 on 2023-08-23 07:20
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_alter_ordervariantspromotion_line_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCompany",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=256, unique=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Ghn"),
                            (2, "Vn Post"),
                            (3, "E Commerce"),
                            (4, "Grab"),
                            (5, "Lalamove"),
                            (6, "Viettel Post"),
                            (0, "Other"),
                        ]
                    ),
                ),
                ("ghn_token", models.TextField(null=True)),
                ("ghn_shop_id", models.CharField(max_length=255, null=True)),
                ("vn_post_username", models.CharField(max_length=255, null=True)),
                ("vn_post_password", models.CharField(max_length=255, null=True)),
                ("vn_post_token", models.TextField(null=True)),
            ],
            options={
                "db_table": "tbl_Delivery_Companies",
            },
        ),
        migrations.CreateModel(
            name="HistoricalShipment",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "carrier_status",
                    models.CharField(
                        choices=[
                            ("delivering", "Delivering"),
                            ("waiting_for_delivery", "Waiting For Delivery"),
                            ("return_transporting", "Return Transporting"),
                            ("delivered", "Delivered"),
                            ("waiting_to_return", "Waiting To Return"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "carrier_status_system",
                    models.CharField(
                        choices=[
                            ("delivering", "Delivering"),
                            ("waiting_for_delivery", "Waiting For Delivery"),
                            ("return_transporting", "Return Transporting"),
                            ("delivered", "Delivered"),
                            ("waiting_to_return", "Waiting To Return"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "carrier_status_manual",
                    models.CharField(
                        choices=[
                            ("delivering", "Delivering"),
                            ("waiting_for_delivery", "Waiting For Delivery"),
                            ("return_transporting", "Return Transporting"),
                            ("delivered", "Delivered"),
                            ("waiting_to_return", "Waiting To Return"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_cod_transferred", models.BooleanField(default=False)),
                ("cod_transfer_date", models.DateTimeField(null=True)),
                ("tracking_number", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
            ],
            options={
                "verbose_name": "historical shipment",
                "verbose_name_plural": "historical shipments",
                "db_table": "tbl_Delivery_Shipment_Historical",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("shipping_order_id", models.CharField(max_length=255, null=True)),
                ("return_address", models.CharField(max_length=255)),
                ("return_ward_code", models.CharField(max_length=255)),
                ("return_phone", models.CharField(max_length=255)),
                ("return_name", models.CharField(max_length=255)),
                ("return_full_address", models.TextField()),
                ("to_phone", models.CharField(max_length=255)),
                ("to_name", models.CharField(max_length=255)),
                ("to_ward_code", models.CharField(max_length=255, null=True)),
                ("to_address", models.CharField(max_length=255, null=True)),
                ("to_full_address", models.TextField(null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "service_type_id",
                    models.IntegerField(
                        choices=[
                            (1, "CHUAN"),
                            (2, "NHANH"),
                            (3, "TIET_KIEM"),
                            (4, "EMS"),
                            (5, "BK"),
                            (6, "ECOD"),
                            (7, "DONG_GIA"),
                            (8, "BKCOD"),
                            (0, "OTHER"),
                        ],
                        null=True,
                    ),
                ),
                ("payment_type_id", models.IntegerField(choices=[(1, "Shop Payment"), (2, "Buyer Payment")], null=True)),
                ("required_note", models.CharField(max_length=255, null=True)),
                ("trans_type", models.CharField(max_length=255, null=True)),
                ("client_order_code", models.CharField(max_length=255, null=True)),
                ("cod_amount", models.IntegerField(null=True)),
                ("insurance_value", models.IntegerField(null=True)),
                ("picking_ship", models.IntegerField(null=True)),
                ("weight", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("length", models.IntegerField(null=True)),
                (
                    "carrier_status",
                    models.CharField(
                        choices=[
                            ("delivering", "Delivering"),
                            ("waiting_for_delivery", "Waiting For Delivery"),
                            ("return_transporting", "Return Transporting"),
                            ("delivered", "Delivered"),
                            ("waiting_to_return", "Waiting To Return"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "carrier_status_system",
                    models.CharField(
                        choices=[
                            ("delivering", "Delivering"),
                            ("waiting_for_delivery", "Waiting For Delivery"),
                            ("return_transporting", "Return Transporting"),
                            ("delivered", "Delivered"),
                            ("waiting_to_return", "Waiting To Return"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "carrier_status_manual",
                    models.CharField(
                        choices=[
                            ("delivering", "Delivering"),
                            ("waiting_for_delivery", "Waiting For Delivery"),
                            ("return_transporting", "Return Transporting"),
                            ("delivered", "Delivered"),
                            ("waiting_to_return", "Waiting To Return"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_cod_transferred", models.BooleanField(default=False)),
                ("cod_transfer_date", models.DateTimeField(null=True)),
                ("finish_date", models.DateTimeField(null=True)),
                ("tracking_number", models.CharField(max_length=255, null=True)),
                ("expected_delivery_time", models.DateTimeField(null=True)),
                ("delivery_company_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "delivery_company_type",
                    models.IntegerField(
                        choices=[
                            (1, "Ghn"),
                            (2, "Vn Post"),
                            (3, "E Commerce"),
                            (4, "Grab"),
                            (5, "Lalamove"),
                            (6, "Viettel Post"),
                            (0, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("items", models.JSONField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_company",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="delivery.deliverycompany"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="shipping", to="orders.orders")),
            ],
            options={
                "db_table": "tbl_Delivery_Shipments",
            },
        ),
    ]
