# Generated by Django 4.2.4 on 2023-08-31 06:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverycompany",
            name="vn_post_customer_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="required_note",
            field=models.CharField(
                choices=[
                    ("CHOTHUHANG", "Cho Thu Hang"),
                    ("CHOXEMHANGKHONGTHU", "Cho Xem Hang Khong Thu"),
                    ("KHONGCHOXEMHANG", "Khong Cho Xem Hang"),
                ],
                max_length=255,
            ),
        ),
    ]
