# Generated by Django 4.2.4 on 2023-09-08 04:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_deliverycompany_vn_post_customer_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="shipping_order_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
