# Generated by Django 4.2.5 on 2023-10-23 03:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_alter_shipment_shipping_order_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverycompany",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="shipment",
            options={"ordering": ["-created"]},
        ),
    ]
