# Generated by Django 4.2.9 on 2024-02-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliverycompany_options_alter_shipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycompany',
            name='vtpost_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='vtpost_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
