# Generated by Django 5.0 on 2024-03-20 03:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_deliverycompany_vtpost_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverycompany",
            name="vtpost_user_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
