# Generated by Django 5.0 on 2025-04-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverycompany_vtpost_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_company',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='sheet_export',
        ),
        migrations.DeleteModel(
            name='HistoricalShipment',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
