# Generated by Django 5.0 on 2025-04-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_shipment_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCompany',
        ),
    ]
