# Generated by Django 4.2.3 on 2023-07-21 03:36
import uuid

import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.db import migrations
from django.db import models

import leads.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalLead",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=30)),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("0", "SPAM"),
                            ("1", "NEW"),
                            ("2", "WAITING"),
                            ("3", "PROCESS"),
                            ("4", "YES"),
                            ("5", "NO"),
                            ("6", "CONSIDER"),
                            ("7", "BAD_DATA"),
                        ],
                        default=leads.enums.LeadStatus["NEW"],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=500, null=True)),
                ("handle_assigned_at", models.DateTimeField(null=True)),
                ("processdone_at", models.DateTimeField(null=True)),
                ("call_later_at", models.DateTimeField(null=True)),
                ("call_handle_number", models.IntegerField(null=True)),
                ("landingpage_url", models.URLField(blank=True, null=True)),
                ("landingpage_domain", models.URLField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_channel", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_id_content", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_id", models.CharField(blank=True, max_length=255, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("is_new_customer", models.BooleanField(default=False)),
                ("is_existed", models.BooleanField(default=False)),
                ("is_duplicated_ip", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical lead",
                "verbose_name_plural": "historical leads",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=30)),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("0", "SPAM"),
                            ("1", "NEW"),
                            ("2", "WAITING"),
                            ("3", "PROCESS"),
                            ("4", "YES"),
                            ("5", "NO"),
                            ("6", "CONSIDER"),
                            ("7", "BAD_DATA"),
                        ],
                        default=leads.enums.LeadStatus["NEW"],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=500, null=True)),
                ("handle_assigned_at", models.DateTimeField(null=True)),
                ("processdone_at", models.DateTimeField(null=True)),
                ("call_later_at", models.DateTimeField(null=True)),
                ("call_handle_number", models.IntegerField(null=True)),
                ("landingpage_url", models.URLField(blank=True, null=True)),
                ("landingpage_domain", models.URLField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_channel", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_id_content", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_id", models.CharField(blank=True, max_length=255, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("is_new_customer", models.BooleanField(default=False)),
                ("is_existed", models.BooleanField(default=False)),
                ("is_duplicated_ip", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tbl_Leads",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadAfterBadDataReason",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("is_shown", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tbl_Leads_After_Bad_Data_Reasons",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadChannel",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("is_shown", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tbl_Leads_Channels",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadFailReason",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("is_shown", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tbl_Leads_Fail_Reasons",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadFanpage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("is_shown", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tbl_Leads_Fanpages",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadHandleReason",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("is_shown", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tbl_Leads_Handle_Reasons",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadMappingProducts",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("landingpage_url", models.URLField()),
            ],
            options={
                "db_table": "tbl_Leads_Mapping_Products",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadPreBadDataReason",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("is_shown", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tbl_Leads_Pre_Bad_Data_Reasons",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadProduct",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("is_shown", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tbl_Leads_Products",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LeadTag",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "tbl_Leads_Tags",
                "ordering": ["-created"],
            },
        ),
    ]
