# Generated by Django 4.2.3 on 2023-07-21 04:47
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicallead",
            old_name="landingpage_domain",
            new_name="landing_page_domain",
        ),
        migrations.RenameField(
            model_name="historicallead",
            old_name="landingpage_url",
            new_name="landing_page_url",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="landingpage_domain",
            new_name="landing_page_domain",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="landingpage_url",
            new_name="landing_page_url",
        ),
        migrations.RenameField(
            model_name="leadmappingproducts",
            old_name="landingpage_url",
            new_name="landing_page_url",
        ),
    ]
