# Generated by Django 4.2.4 on 2023-08-17 03:11
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_rename_landingpage_domain_historicallead_landing_page_domain_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historicallead",
            table="tbl_Leads_Historical",
        ),
    ]
