# Generated by Django 4.2.4 on 2023-08-17 04:39
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_ordervariantspromotion_line_item"),
        ("leads", "0004_alter_historicallead_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.orders",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lead_orders", to="orders.orders"
            ),
        ),
    ]
