# Generated by Django 4.2.4 on 2023-08-17 08:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_historicallead_order_lead_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadtag",
            name="is_shown",
            field=models.BooleanField(default=True),
        ),
    ]
