# Generated by Django 4.2.4 on 2023-09-14 03:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_leadtag_is_shown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallead",
            name="call_handle_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lead",
            name="call_handle_number",
            field=models.IntegerField(default=0),
        ),
    ]
