# Generated by Django 4.2.5 on 2023-10-17 06:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_alter_historicallead_call_handle_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallead",
            name="created_by",
        ),
        migrations.AddField(
            model_name="historicallead",
            name="order_key",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="order_key",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
