# Generated by Django 4.2.7 on 2023-12-20 06:32
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_department_sub_historicaluser_department_sub_and_more"),
        ("leads", "0008_remove_historicallead_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="department_sub",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.department_sub",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="department_sub",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lead_department_sub", to="users.department_sub"
            ),
        ),
    ]
