# Generated by Django 4.2.7 on 2023-12-26 02:47
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_historicallead_department_sub_lead_department_sub"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalLead",
        ),
    ]
