# Generated by Django 4.2.7 on 2023-12-26 02:48
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_department_sub_historicaluser_department_sub_and_more"),
        ("leads", "0010_delete_historicallead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="department_sub",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads_department_sub", to="users.department_sub"
            ),
        ),
    ]
