# Generated by Django 4.2.7 on 2023-12-26 02:48
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models

import leads.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0013_alter_customer_options_alter_customergroup_options_and_more"),
        ("users", "0008_rename_department_sub_departmentsub"),
        ("orders", "0012_historicalorders_complete_by_orders_complete_by"),
        ("leads", "0011_alter_lead_department_sub"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLead",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=30)),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("0", "SPAM"),
                            ("1", "NEW"),
                            ("2", "WAITING"),
                            ("3", "PROCESS"),
                            ("4", "YES"),
                            ("5", "NO"),
                            ("6", "CONSIDER"),
                            ("7", "BAD_DATA"),
                        ],
                        default=leads.enums.LeadStatus["NEW"],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=500, null=True)),
                ("handle_assigned_at", models.DateTimeField(null=True)),
                ("processdone_at", models.DateTimeField(null=True)),
                ("call_later_at", models.DateTimeField(null=True)),
                ("call_handle_number", models.IntegerField(default=0)),
                ("landing_page_url", models.URLField(blank=True, null=True)),
                ("landing_page_domain", models.URLField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_channel", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_id_content", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_id", models.CharField(blank=True, max_length=255, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("is_new_customer", models.BooleanField(default=False)),
                ("is_existed", models.BooleanField(default=False)),
                ("is_duplicated_ip", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
                ("order_key", models.CharField(max_length=50, null=True)),
                ("history_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "after_bad_data_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadafterbaddatareason",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadchannel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="customers.customer",
                    ),
                ),
                (
                    "department_sub",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="users.departmentsub",
                    ),
                ),
                (
                    "fail_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadfailreason",
                    ),
                ),
                (
                    "fanpage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadfanpage",
                    ),
                ),
                (
                    "handle_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handle_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadhandlereason",
                    ),
                ),
                (
                    "handle_telesales",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.orders",
                    ),
                ),
                (
                    "pre_bad_data_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadprebaddatareason",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical lead",
                "verbose_name_plural": "historical leads",
                "db_table": "tbl_Leads_Historical",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
