# Generated by Django 4.2.7 on 2024-03-05 03:15
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productsvariants_sales_bonus"),
        ("leads", "0012_historicallead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallead",
            name="product",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="product",
        ),
        migrations.AddField(
            model_name="historicallead",
            name="product_category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="product_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="product_categories", to="products.productcategory"
            ),
        ),
    ]
