# Generated by Django 4.2.7 on 2024-03-12 03:26
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productsvariants_sales_bonus"),
        ("leads", "0013_remove_historicallead_product_remove_lead_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallead",
            name="department_sub",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="department_sub",
        ),
        migrations.RemoveField(
            model_name="leadmappingproducts",
            name="product",
        ),
        migrations.AddField(
            model_name="leadmappingproducts",
            name="product_category",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="products.productcategory"),
        ),
    ]
