# Generated by Django 5.0 on 2024-03-29 11:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_remove_historicallead_department_sub_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallead",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
