# Generated by Django 5.0 on 2024-04-02 04:53
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0015_alter_historicallead_name_alter_lead_name"),
        ("users", "0013_department_is_receive_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="department",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="department", to="users.department"
            ),
        ),
    ]
