# Generated by Django 5.0 on 2024-04-10 06:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_historicallead_department_lead_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="department_assigned_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="department_assigned_at",
            field=models.DateTimeField(null=True),
        ),
    ]
