# Generated by Django 5.0 on 2025-06-12 18:56

import customers.enums
import django.core.validators
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('lead', 'LEAD'), ('order', 'ORDER'), ('upload_file', 'UPLOAD_FILE'), ('other', 'OTHER')], default=customers.enums.SourceLead['OTHER'], max_length=11)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'FEMALE'), ('male', 'MALE'), ('other', 'OTHER')], max_length=10, null=True)),
                ('customer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('ecommerce_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ranking', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_up_rank_date', models.DateField(blank=True, null=True)),
                ('total_order', models.IntegerField(blank=True, default=0, null=True)),
                ('total_spent', models.FloatField(blank=True, default=0, null=True)),
                ('last_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_order_time', models.DateTimeField(blank=True, null=True)),
                ('care_start_time', models.DateTimeField(blank=True, null=True)),
                ('shipping_completed_order', models.IntegerField(default=0)),
                ('shipping_completed_spent', models.IntegerField(default=0)),
                ('last_shipping_completed', models.DateTimeField(blank=True, null=True)),
                ('shipping_return_order', models.IntegerField(default=0)),
                ('shipping_return_spent', models.IntegerField(default=0)),
                ('shipping_cancel_order', models.IntegerField(default=0)),
                ('shipping_cancel_spent', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_Customers',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_Customers_Group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroupDetail',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_Customers_Group_Detail',
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a Vietnamese phone number,             include 7-15 digits. Example format: 098xxxxxxx, +8498xxxxxxx', regex='[0|+84|84]{0,4}[9|8|3|5|7]{1}[0-9]{6,10}')])),
            ],
            options={
                'db_table': 'tbl_Customers_Phone',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRank',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_rank', models.CharField(max_length=255, unique=True)),
                ('spend_from', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('spend_to', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'tbl_Rank',
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tbl_Customers_Tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTagDetail',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_Customers_Tag_Detail',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('source', models.CharField(choices=[('lead', 'LEAD'), ('order', 'ORDER'), ('upload_file', 'UPLOAD_FILE'), ('other', 'OTHER')], default=customers.enums.SourceLead['OTHER'], max_length=11)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'FEMALE'), ('male', 'MALE'), ('other', 'OTHER')], max_length=10, null=True)),
                ('customer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('ecommerce_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ranking', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_up_rank_date', models.DateField(blank=True, null=True)),
                ('total_order', models.IntegerField(blank=True, default=0, null=True)),
                ('total_spent', models.FloatField(blank=True, default=0, null=True)),
                ('last_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_order_time', models.DateTimeField(blank=True, null=True)),
                ('care_start_time', models.DateTimeField(blank=True, null=True)),
                ('shipping_completed_order', models.IntegerField(default=0)),
                ('shipping_completed_spent', models.IntegerField(default=0)),
                ('last_shipping_completed', models.DateTimeField(blank=True, null=True)),
                ('shipping_return_order', models.IntegerField(default=0)),
                ('shipping_return_spent', models.IntegerField(default=0)),
                ('shipping_cancel_order', models.IntegerField(default=0)),
                ('shipping_cancel_spent', models.IntegerField(default=0)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical customer',
                'verbose_name_plural': 'historical customers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
