# Generated by Django 4.2.3 on 2023-07-20 02:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerAdress",
            new_name="CustomerAddress",
        ),
    ]
