# Generated by Django 4.2.3 on 2023-07-20 06:25
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("customers", "0002_rename_customeradress_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="ward",
            field=models.ForeignKey(
                default="0019",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="customer_address",
                to="locations.wards",
            ),
            preserve_default=False,
        ),
    ]
