# Generated by Django 4.2.3 on 2023-07-20 08:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customeraddress_is_default_customeraddress_ward"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customerphone",
            table="tbl_Customers_Phone",
        ),
    ]
