# Generated by Django 4.2.3 on 2023-07-24 04:36
import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_customerphone_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customeraddress",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="customerphone",
            options={"ordering": ["created"]},
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="number_of_times",
        ),
        migrations.RemoveField(
            model_name="customerphone",
            name="number_of_times",
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="created",
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="customerphone",
            name="created",
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created"),
        ),
        migrations.AddField(
            model_name="customerphone",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="customerphone",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be a Vietnamese phone number, include 7-15 digits. Example format: 098xxxxxxx, +8498xxxxxxx",
                        regex="[0|+84|84]{0,4}[9|8|3|5|7]{1}[0-9]{6,10}",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="customergroupdetail",
            constraint=models.UniqueConstraint(fields=("customer_group", "customer"), name="unique_customer_group"),
        ),
        migrations.AddConstraint(
            model_name="customertagdetail",
            constraint=models.UniqueConstraint(fields=("customer_tag", "customer"), name="unique_customer_tag"),
        ),
    ]
