# Generated by Django 4.2.3 on 2023-07-24 08:56
import uuid

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customeraddress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcustomer",
            name="id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customerphone",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be a Vietnamese phone number,             include 7-15 digits. Example format: 098xxxxxxx, +8498xxxxxxx",
                        regex="[0|+84|84]{0,4}[9|8|3|5|7]{1}[0-9]{6,10}",
                    )
                ],
            ),
        ),
    ]
