# Generated by Django 4.2.3 on 2023-07-28 08:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_historicalcustomer_id_alter_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="addresses", to="customers.customer"
            ),
        ),
    ]
