# Generated by Django 4.2.4 on 2023-08-15 08:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_alter_customeraddress_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="return_completed_order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="return_completed_spent",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_completed_order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_completed_spent",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="return_completed_order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="return_completed_spent",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="shipping_completed_order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="shipping_completed_spent",
            field=models.IntegerField(null=True),
        ),
    ]
