# Generated by Django 4.2.4 on 2023-08-15 08:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_customer_return_completed_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="return_completed_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="return_completed_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="shipping_completed_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="shipping_completed_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="return_completed_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="return_completed_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="shipping_completed_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="shipping_completed_spent",
            field=models.IntegerField(default=0),
        ),
    ]
