# Generated by Django 4.2.4 on 2023-08-16 10:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_alter_customer_return_completed_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="return_completed_order",
            new_name="shipping_cancel_order",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="return_completed_spent",
            new_name="shipping_cancel_spent",
        ),
        migrations.RenameField(
            model_name="historicalcustomer",
            old_name="return_completed_order",
            new_name="shipping_cancel_order",
        ),
        migrations.RenameField(
            model_name="historicalcustomer",
            old_name="return_completed_spent",
            new_name="shipping_cancel_spent",
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_return_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_return_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="shipping_return_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="shipping_return_spent",
            field=models.IntegerField(default=0),
        ),
    ]
