# Generated by Django 4.2.5 on 2023-09-18 06:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_rename_return_completed_order_customer_shipping_cancel_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeraddress",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="ward",
        ),
    ]
