# Generated by Django 4.2.5 on 2023-09-18 06:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_historicalorders_address_shipping_and_more"),
        ("customers", "0011_remove_customeraddress_customer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerAddress",
        ),
    ]
