# Generated by Django 4.2.5 on 2023-10-23 03:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_delete_customeraddress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="customergroup",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="customerphone",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="customertag",
            options={"ordering": ["name"]},
        ),
    ]
