# Generated by Django 5.0 on 2024-05-31 06:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0013_alter_customer_options_alter_customergroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
