# Generated by Django 5.0 on 2024-06-04 10:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0014_customergroup_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
