# Generated by Django 5.0 on 2025-06-12 18:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'tbl_Products_Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductsMaterials',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('SKU_code', models.CharField(max_length=255, unique=True)),
                ('bar_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('length', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('height', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('width', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('neo_price', models.BigIntegerField(null=True)),
                ('sale_price', models.BigIntegerField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_Products_Materials',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, unique=True)),
                ('business_code', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=20)),
                ('legal_representative', models.CharField(blank=True, max_length=256, null=True)),
                ('established_at', models.DateField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'tbl_Products_Supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductsVariants',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('SKU_code', models.CharField(max_length=255, unique=True)),
                ('bar_code', models.CharField(blank=True, max_length=255, null=True)),
                ('purchare_price', models.PositiveIntegerField(null=True)),
                ('neo_price', models.BigIntegerField(null=True)),
                ('sale_price', models.BigIntegerField(null=True)),
                ('sales_bonus', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('simple', 'SIMPLE'), ('bundle', 'BUNDLE'), ('combo', 'COMBO')], default='simple', max_length=6)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_Products_Variants',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductsVariantsBatches',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('VR', 'VARIANT'), ('MT', 'MATERIAL')], default='VR', max_length=2)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_Products_Variants_Batches',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductsVariantsComboDetail',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_detail_variant', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_Products_Variants_Combo_Detail',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductsVariantsMapping',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('lazada', 'LAZADA'), ('tiktok', 'TIKTOK'), ('shopee', 'SHOPEE')], max_length=6)),
                ('third_product_id', models.CharField(max_length=50)),
                ('third_purchare_price', models.PositiveIntegerField(blank=True, null=True)),
                ('third_neo_price', models.PositiveIntegerField(blank=True, null=True)),
                ('third_sale_price', models.PositiveIntegerField(blank=True, null=True)),
                ('third_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_Products_Variants_Mapping',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductsVariantsMaterials',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
            ],
            options={
                'db_table': 'tbl_Products_Variants_Materials',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'tbl_Products_Tag',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('SKU_code', models.CharField(max_length=255, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'db_table': 'tbl_Products',
                'ordering': ['-created'],
            },
        ),
    ]
