# Generated by Django 4.2.3 on 2023-07-25 06:32
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                "db_table": "tbl_Products_Attribute",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("code", models.CharField(max_length=32, null=True, unique=True)),
            ],
            options={
                "db_table": "tbl_Products_Category",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("note", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="products.productcategory"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="product_create", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="product_modify", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Products",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=256, unique=True)),
                ("business_code", models.CharField(blank=True, max_length=256, null=True)),
                ("tax_number", models.CharField(blank=True, max_length=256, null=True)),
                ("country", models.CharField(blank=True, max_length=256, null=True)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                ("status", models.CharField(choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")], default="ACTIVE", max_length=20)),
                ("legal_representative", models.CharField(blank=True, max_length=256, null=True)),
                ("established_at", models.DateField(blank=True, max_length=256, null=True)),
            ],
            options={
                "db_table": "tbl_Products_Supplier",
            },
        ),
        migrations.CreateModel(
            name="ProductsVariants",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("note", models.TextField()),
                ("SKU_code", models.CharField(max_length=255, unique=True)),
                ("bar_code", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("purchare_price", models.PositiveIntegerField(null=True)),
                ("neo_price", models.PositiveIntegerField(null=True)),
                ("sale_price", models.PositiveIntegerField(null=True)),
                ("status", models.CharField(choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")], default="ACTIVE", max_length=8)),
                (
                    "type",
                    models.CharField(
                        choices=[("simple", "SIMPLE"), ("bundle", "BUNDLE"), ("combo", "COMBO")], default="simple", max_length=6
                    ),
                ),
                ("attributes", models.ManyToManyField(related_name="product_variant_attributes", to="products.productattribute")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_variants_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_variants_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.products"),
                ),
            ],
            options={
                "db_table": "tbl_Products_Variants",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tag", models.CharField(blank=True, max_length=64, unique=True)),
            ],
            options={
                "db_table": "tbl_Products_Tag",
            },
        ),
        migrations.CreateModel(
            name="ProductsVariantsComboDetail",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("price_detail_variant", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "detail_variant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="combos", to="products.productsvariants"),
                ),
                (
                    "origin_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="combo_variants", to="products.productsvariants"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Products_Variants_Combo_Detail",
            },
        ),
        migrations.AddField(
            model_name="productsvariants",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="product_variant_tags", to="products.producttag"),
        ),
        migrations.AddField(
            model_name="products",
            name="supplier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="products", to="products.productsupplier"
            ),
        ),
        migrations.CreateModel(
            name="ProductAttributeDetail",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.CharField(blank=True, max_length=128)),
                (
                    "attribute",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="details", to="products.productattribute"),
                ),
            ],
            options={
                "db_table": "tbl_Products_Attribute_Detail",
            },
        ),
        migrations.CreateModel(
            name="ProductsVariantsMapping",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(choices=[("lazada", "LAZADA"), ("tiktok", "TIKTOK"), ("shopee", "SHOPEE")], max_length=6)),
                ("third_product_id", models.CharField(max_length=50)),
                ("third_purchare_price", models.PositiveIntegerField(blank=True, null=True)),
                ("third_neo_price", models.PositiveIntegerField(blank=True, null=True)),
                ("third_sale_price", models.PositiveIntegerField(blank=True, null=True)),
                ("third_image", models.URLField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_mapping_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_mapping_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mappings", to="products.productsvariants"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Products_Variants_Mapping",
                "unique_together": {("third_product_id", "product_variant")},
            },
        ),
        migrations.CreateModel(
            name="ProductsVariantsBatches",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("expire_date", models.DateField(blank=True, null=True)),
                (
                    "product_variant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="batches", to="products.productsvariants"),
                ),
            ],
            options={
                "db_table": "tbl_Products_Variants_Batches",
                "unique_together": {("product_variant", "name")},
            },
        ),
    ]
