# Generated by Django 4.2.3 on 2023-07-25 07:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattributedetail",
            name="attribute",
        ),
        migrations.RemoveField(
            model_name="productsvariants",
            name="attributes",
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
        migrations.DeleteModel(
            name="ProductAttributeDetail",
        ),
    ]
