# Generated by Django 5.0 on 2025-09-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created'], 'permissions': [('view_variant_image', 'Can view variant image')]},
        ),
    ]
