# Generated by Django 4.2.3 on 2023-07-25 08:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_productattributedetail_attribute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productsvariants",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
