# Generated by Django 4.2.5 on 2023-10-23 03:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_products_note_alter_productsvariants_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="productsupplier",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productsvariants",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="productsvariantsbatches",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="productsvariantscombodetail",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="productsvariantsmapping",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="producttag",
            options={"ordering": ["tag"]},
        ),
    ]
