# Generated by Django 4.2.5 on 2023-12-21 02:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productcategory_options_alter_products_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsvariants",
            name="sales_bonus",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
