# Generated by Django 4.2.7 on 2024-03-12 05:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productsvariants_sales_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsvariants",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
