# Generated by Django 5.0 on 2024-05-30 10:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productsvariants_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsvariants",
            name="neo_price",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="productsvariants",
            name="sale_price",
            field=models.BigIntegerField(null=True),
        ),
    ]
