# Generated by Django 5.0 on 2024-07-11 08:37
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productsvariants_neo_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productsvariantsbatches",
            name="type",
            field=models.CharField(choices=[("VR", "VARIANT"), ("MT", "MATERIAL")], default="VR", max_length=2),
        ),
        migrations.AlterField(
            model_name="productsvariantsbatches",
            name="product_variant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="batches", to="products.productsvariants"
            ),
        ),
        migrations.CreateModel(
            name="ProductsMaterials",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True, null=True)),
                ("SKU_code", models.CharField(max_length=255, unique=True)),
                ("bar_code", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("neo_price", models.BigIntegerField(null=True)),
                ("sale_price", models.BigIntegerField(null=True)),
                ("status", models.CharField(choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")], default="ACTIVE", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_materials_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_materials_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Products_Materials",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="productsvariantsbatches",
            name="product_material",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="batches", to="products.productsmaterials"
            ),
        ),
        migrations.CreateModel(
            name="ProductsVariantsMaterials",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "product_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.productsmaterials"
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="products.productsvariants"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Products_Variants_Materials",
                "ordering": ["-created"],
            },
        ),
    ]
