# Generated by Django 5.0 on 2024-07-15 07:23
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productsvariantsmaterials_product_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsvariantsmaterials",
            name="product_material",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.productsmaterials"),
        ),
        migrations.AlterField(
            model_name="productsvariantsmaterials",
            name="product_variant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="products.productsvariants"),
        ),
    ]
