# Generated by Django 5.0 on 2024-07-16 06:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_productsvariantsmaterials_product_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="SKU_code",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productsvariants",
            name="commission",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="productsvariants",
            name="commission_percent",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="productsvariants",
            name="bar_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
