# Generated by Django 5.0 on 2024-07-17 02:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_products_sku_code_productsvariants_commission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsvariants",
            name="height",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="productsvariants",
            name="mass",
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="productsvariants",
            name="width",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
