# Generated by Django 5.0 on 2024-07-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productsvariants_height_productsvariants_mass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsvariants',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productsvariants',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='productsvariants',
            name='width',
        ),
    ]
