# Generated by Django 5.0 on 2024-07-18 06:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_remove_productsvariants_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsmaterials",
            name="height",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="productsmaterials",
            name="length",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="productsmaterials",
            name="weight",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="productsmaterials",
            name="width",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
