# Generated by Django 5.0 on 2024-07-18 07:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_productsmaterials_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsvariantsmaterials",
            name="weight",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
