# Generated by Django 5.0 on 2024-09-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productsvariantsmaterials_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsvariantsbatches',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
