# Generated by Django 4.2.9 on 2024-01-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VnPostWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text='When we received the event.')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='webhook_vnp_receive_52c09b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViettelPostWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text='When we received the event.')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='webhook_vie_receive_73ffd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='GHNWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('shop_id', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(help_text='When we received the event.')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='webhook_ghn_receive_9c6636_idx')],
            },
        ),
    ]
