# Generated by Django 5.0 on 2025-04-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GHNWebhook',
        ),
        migrations.DeleteModel(
            name='ViettelPostWebhook',
        ),
        migrations.DeleteModel(
            name='VnPostWebhook',
        ),
    ]
