# Generated by Django 4.2.4 on 2023-08-10 04:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaluser",
            old_name="phongban",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phongban",
            new_name="department",
        ),
        migrations.AddField(
            model_name="role",
            name="default_router",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="historicaluser",
            table="tbl_User_Historical",
        ),
    ]
