# Generated by Django 4.2.5 on 2023-10-16 14:34
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_historicaluser_modified_by_user_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
    ]
