# Generated by Django 4.2.5 on 2023-10-16 14:36
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupuser",
            name="users",
            field=models.ManyToManyField(
                blank=True, db_table="tbl_User_GroupsUsers", related_name="groups_participated", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
