# Generated by Django 4.2.5 on 2023-10-23 03:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_groupuser_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
