# Generated by Django 4.2.7 on 2023-12-20 06:32
import uuid

import django.db.models.deletion
import model_utils.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_role_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department_Sub",
            fields=[
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "tbl_User_Department_Sub",
            },
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="department_sub",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.department_sub",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department_sub",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.department_sub"),
        ),
    ]
