# Generated by Django 4.2.7 on 2023-12-26 02:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_alter_lead_department_sub"),
        ("users", "0007_department_sub_historicaluser_department_sub_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Department_Sub",
            new_name="DepartmentSub",
        ),
    ]
