# Generated by Django 4.2.7 on 2023-12-26 09:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_department_sub_departmentsub"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_shown",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="departmentsub",
            name="is_shown",
            field=models.BooleanField(default=False),
        ),
    ]
