# Generated by Django 4.2.7 on 2023-12-27 04:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_department_is_shown_departmentsub_is_shown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="departmentsub",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
