# Generated by Django 4.2.7 on 2024-03-12 03:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_remove_historicallead_department_sub_and_more"),
        ("users", "0010_alter_department_name_alter_departmentsub_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="department_sub",
        ),
        migrations.RemoveField(
            model_name="user",
            name="department_sub",
        ),
        migrations.DeleteModel(
            name="DepartmentSub",
        ),
    ]
