# Generated by Django 5.0 on 2024-03-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_historicaluser_department_sub_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupUser',
        ),
    ]
