# Generated by Django 5.0 on 2024-04-02 04:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_delete_groupuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_receive_lead",
            field=models.BooleanField(default=False),
        ),
    ]
