# Generated by Django 5.0 on 2024-04-22 03:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_department_is_receive_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_assign_lead_campaign",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_assign_lead_campaign",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
