# Generated by Django 5.0 on 2024-06-13 08:39
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0014_historicaluser_is_assign_lead_campaign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=255)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="action_logs", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
