# Generated by Django 5.0 on 2024-06-13 08:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_useractionlog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="useractionlog",
            table="tbl_User_Action_Log",
        ),
    ]
