# Generated by Django 5.0 on 2024-06-17 10:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_useractionlog_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractionlog",
            name="object_id",
        ),
        migrations.AddField(
            model_name="useractionlog",
            name="object_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useractionlog",
            name="data",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
