# Generated by Django 5.0 on 2024-06-17 10:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_useractionlog_object_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useractionlog",
            old_name="object_uuid",
            new_name="object_id",
        ),
    ]
