# Generated by Django 5.0 on 2024-06-19 04:42
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0018_rename_object_uuid_useractionlog_object_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractionlog",
            options={"ordering": ["-action_time"]},
        ),
        migrations.RenameField(
            model_name="useractionlog",
            old_name="timestamp",
            new_name="action_time",
        ),
        migrations.RemoveField(
            model_name="useractionlog",
            name="action",
        ),
        migrations.AddField(
            model_name="useractionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("Create", "Create"),
                    ("Read", "Read"),
                    ("Update", "Update"),
                    ("Delete", "Delete"),
                    ("Login", "Login"),
                    ("Logout", "Logout"),
                    ("Login Failed", "Login Failed"),
                ],
                default="Read",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="useractionlog",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractionlog",
            name="status",
            field=models.CharField(choices=[("Success", "Success"), ("Failed", "Failed")], default="Success", max_length=15),
        ),
        migrations.AlterField(
            model_name="useractionlog",
            name="content_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype"),
        ),
        migrations.AlterField(
            model_name="useractionlog",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
