# Generated by Django 5.0 on 2024-06-20 03:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_useractionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractionlog",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
