# Generated by Django 5.0 on 2024-06-20 09:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_useractionlog_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useractionlog",
            old_name="remarks",
            new_name="action_name",
        ),
    ]
