# Generated by Django 5.0 on 2024-06-28 08:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_rename_remarks_useractionlog_action_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("Create", "Create"),
                    ("Read", "Read"),
                    ("Update", "Update"),
                    ("Delete", "Delete"),
                    ("Login", "Login"),
                    ("Logout", "Logout"),
                    ("Export", "Export"),
                    ("Import", "Import"),
                ],
                default="Read",
                max_length=100,
            ),
        ),
    ]
