# Generated by Django 5.0 on 2025-06-12 18:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IP', 'IMPORT'), ('EP', 'EXPORT'), ('TF', 'TRANSFER'), ('CK', 'CHECK'), ('OD', 'ORDER'), ('TURN', 'TURN')], max_length=10, unique=True)),
                ('value', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'tbl_Sequence_Identity',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWarehouseInventoryAvailable',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('quantity_confirm', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('quantity_non_confirm', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('quantity_export', models.DecimalField(decimal_places=4, default=0.0, max_digits=15, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.productsvariants')),
            ],
            options={
                'verbose_name': 'historical warehouse inventory available',
                'verbose_name_plural': 'historical warehouse inventory availables',
                'db_table': 'tbl_Warehouse_Inventory_Available_Historical',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_sales', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_Warehouse',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWarehouseInventory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_variant_batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.productsvariantsbatches')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'historical warehouse inventory',
                'verbose_name_plural': 'historical warehouse inventorys',
                'db_table': 'tbl_Warehouse_Inventory_Historical',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WarehouseInventoryAvailable',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('quantity_confirm', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('quantity_non_confirm', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('quantity_export', models.DecimalField(decimal_places=4, default=0.0, max_digits=15, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_available_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_available_modified', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_available_product_variant', to='products.productsvariants')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Inventory_Available',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventoryReason',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IP', 'IMPORT'), ('EP', 'EXPORT'), ('TF', 'TRANSFER'), ('CK', 'CHECK')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_reason_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_reason_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_Warehouse_Inventory_Reason',
                'ordering': ['-created'],
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventoryLog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('type', models.CharField(choices=[('IP', 'IMPORT'), ('EP', 'EXPORT'), ('TF', 'TRANSFER'), ('CK', 'CHECK')], max_length=2)),
                ('sheet_code', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_log_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_log_modified', to=settings.AUTH_USER_MODEL)),
                ('product_variant_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_log_product_variant_batch', to='products.productsvariantsbatches')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_log_warehouse', to='warehouses.warehouse')),
                ('change_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory_log_change_reason', to='warehouses.warehouseinventoryreason')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Inventory_Logs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSheetCheck',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('CK', 'CHECK')], max_length=2)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_confirm', models.BooleanField(default=False)),
                ('change_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sheet_check_change_reason', to='warehouses.warehouseinventoryreason')),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_confirm_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_modified', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_warehouse', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Sheet_Check',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSheetCheckDetail',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_system', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('quantity_actual', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_detail_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_detail_modified', to=settings.AUTH_USER_MODEL)),
                ('product_variant_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_detail_product_variant_batch', to='products.productsvariantsbatches')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_check_detail_sheet', to='warehouses.warehousesheetcheck')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Sheet_Check_Detail',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSheetImportExport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('IP', 'IMPORT'), ('EP', 'EXPORT')], max_length=2)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_confirm', models.BooleanField(default=False)),
                ('change_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sheet_import_export_change_reason', to='warehouses.warehouseinventoryreason')),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_confirm_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_modified', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_order', to='orders.orders')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_warehouse', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Sheet_Import_Export',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSheetImportExportDetail',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_detail_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_detail_modified', to=settings.AUTH_USER_MODEL)),
                ('product_variant_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_detail_product_variant_batch', to='products.productsvariantsbatches')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_import_export_detail_sheet', to='warehouses.warehousesheetimportexport')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Sheet_Import_Export_Detail',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSheetTransfer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('TF', 'TRANSFER')], max_length=2)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_confirm', models.BooleanField(default=False)),
                ('change_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sheet_transfer_change_reason', to='warehouses.warehouseinventoryreason')),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_confirm_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_modified', to=settings.AUTH_USER_MODEL)),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_warehouse_from', to='warehouses.warehouse')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_warehouse_to', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Sheet_Transfer',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSheetTransferDetail',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_detail_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_detail_modified', to=settings.AUTH_USER_MODEL)),
                ('product_variant_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_detail_product_variant_batch', to='products.productsvariantsbatches')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_sheet_transfer_detail_sheet', to='warehouses.warehousesheettransfer')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Sheet_Transfer_Detail',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_modified', to=settings.AUTH_USER_MODEL)),
                ('product_variant_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_product_variant_batch', to='products.productsvariantsbatches')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_warehouse', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'tbl_Warehouse_Inventory',
                'ordering': ['-created'],
                'unique_together': {('warehouse', 'product_variant_batch')},
            },
        ),
    ]
