# Generated by Django 4.2.5 on 2023-10-23 03:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0002_remove_warehouse_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sequenceidentity",
            options={"ordering": ["-value"]},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"ordering": ["name"]},
        ),
    ]
