# Generated by Django 4.2.9 on 2024-01-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_alter_sequenceidentity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinventoryavailable',
            name='quantity_export',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
