# Generated by Django 4.2.7 on 2024-03-12 03:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0004_warehouseinventoryavailable_quantity_export"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenceidentity",
            name="type",
            field=models.CharField(
                choices=[("IP", "IMPORT"), ("EP", "EXPORT"), ("TF", "TRANSFER"), ("CK", "CHECK"), ("OD", "ORDER"), ("TURN", "TURN")],
                max_length=10,
                unique=True,
            ),
        ),
    ]
