# Generated by Django 5.0 on 2024-05-11 06:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0005_alter_sequenceidentity_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="warehouseinventoryreason",
            unique_together={("type", "name")},
        ),
    ]
