# Generated by Django 5.0 on 2024-05-22 01:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0006_alter_warehouseinventoryreason_unique_together"),
        ("warehouses", "0006_historicalwarehouseinventory"),
    ]

    operations = []
