# Generated by Django 5.0 on 2024-07-09 03:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0007_merge_20240522_0851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwarehouseinventory",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="warehouseinventory",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="warehouseinventoryavailable",
            name="quantity_confirm",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="warehouseinventoryavailable",
            name="quantity_export",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="warehouseinventoryavailable",
            name="quantity_non_confirm",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="warehouseinventorylog",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="warehousesheetcheckdetail",
            name="quantity_actual",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="warehousesheetcheckdetail",
            name="quantity_system",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="warehousesheetimportexportdetail",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="warehousesheettransferdetail",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
