# Generated by Django 5.0 on 2024-08-27 08:42
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_productsvariantsmaterials_weight"),
        ("warehouses", "0008_alter_historicalwarehouseinventory_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseinventoryavailable",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalWarehouseInventoryAvailable",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("note", models.TextField(blank=True, null=True)),
                ("quantity_confirm", models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ("quantity_non_confirm", models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ("quantity_export", models.DecimalField(decimal_places=4, default=0.0, max_digits=15, null=True)),
                ("history_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.productsvariants",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical warehouse inventory available",
                "verbose_name_plural": "historical warehouse inventory availables",
                "db_table": "tbl_Warehouse_Inventory_Available_Historical",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
