# Generated by Django 5.0 on 2024-09-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0009_warehouseinventoryavailable_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinventorylog',
            name='change_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory_log_change_reason', to='warehouses.warehouseinventoryreason'),
        ),
        migrations.AlterField(
            model_name='warehousesheetimportexport',
            name='change_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sheet_import_export_change_reason', to='warehouses.warehouseinventoryreason'),
        ),
    ]
