# Generated by Django 4.2.3 on 2023-07-20 02:55
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Districts",
            fields=[
                ("name", models.CharField(blank=True, max_length=64)),
                ("slug", models.CharField(max_length=64)),
                ("label", models.CharField(blank=True, max_length=256)),
                (
                    "code",
                    models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False, unique=True),
                ),
                ("ghn_province_id", models.IntegerField(null=True)),
                ("bd_province_id", models.CharField(max_length=256, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("quan", "DISTRICT"), ("huyen", "COUNTY"), ("thi-xa", "TOWN"), ("thanh-pho", "CITY")],
                        default="tinh",
                        max_length=64,
                    ),
                ),
                ("ghn_district_id", models.IntegerField(null=True)),
                ("bd_district_id", models.CharField(max_length=256, null=True)),
            ],
            options={
                "db_table": "tbl_Districts",
            },
        ),
        migrations.CreateModel(
            name="Provinces",
            fields=[
                ("name", models.CharField(blank=True, max_length=64)),
                ("slug", models.CharField(max_length=64)),
                ("label", models.CharField(blank=True, max_length=256)),
                (
                    "code",
                    models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False, unique=True),
                ),
                ("ghn_province_id", models.IntegerField(null=True)),
                ("bd_province_id", models.CharField(max_length=256, null=True)),
                (
                    "type",
                    models.CharField(choices=[("thanh-pho", "CITY"), ("tinh", "PROVINCE")], default="tinh", max_length=64),
                ),
            ],
            options={
                "db_table": "tbl_Provinces",
            },
        ),
        migrations.CreateModel(
            name="Wards",
            fields=[
                ("name", models.CharField(blank=True, max_length=64)),
                ("slug", models.CharField(max_length=64)),
                ("label", models.CharField(blank=True, max_length=256)),
                (
                    "code",
                    models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False, unique=True),
                ),
                ("ghn_province_id", models.IntegerField(null=True)),
                ("bd_province_id", models.CharField(max_length=256, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("phuong", "WARD"), ("xa", "COMMUNE"), ("thi-tran", "TOWN")],
                        default="tinh",
                        max_length=64,
                    ),
                ),
                ("ghn_district_id", models.IntegerField(null=True)),
                ("ghn_ward_id", models.CharField(max_length=16, null=True)),
                ("bd_district_id", models.CharField(max_length=256, null=True)),
                ("bd_ward_id", models.CharField(max_length=256, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district_wards",
                        to="locations.districts",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="province_wards",
                        to="locations.provinces",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Wards",
            },
        ),
        migrations.AddField(
            model_name="districts",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="province_districts",
                to="locations.provinces",
            ),
        ),
    ]
