# Generated by Django 4.2.5 on 2023-09-18 06:37
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models

import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0002_remove_warehouse_address"),
        ("customers", "0011_remove_customeraddress_customer_and_more"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("CT", "CUSTOMER"), ("WH", "WAREHOUSE"), ("OT", "OTHER")],
                        default=locations.models.AddressType["OTHER"],
                        max_length=2,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("address", models.CharField(max_length=1024)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="addresses", to="customers.customer"
                    ),
                ),
                ("ward", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name="addresses", to="locations.wards")),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="addresses", to="warehouses.warehouse"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Addresses",
                "ordering": ["-created"],
            },
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(fields=("customer", "address"), name="unique_customer_address"),
        ),
    ]
