# Generated by Django 4.2.5 on 2023-09-18 06:49
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_address_address_unique_customer_address"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="address",
            name="unique_customer_address",
        ),
    ]
