# Generated by Django 4.2.5 on 2023-10-23 03:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_remove_address_unique_customer_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="districts",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="provinces",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="wards",
            options={"ordering": ["name"]},
        ),
    ]
