# Generated by Django 4.2.9 on 2024-02-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_districts_options_alter_provinces_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='vtpost_district_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='districts',
            name='vtpost_province_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='vtpost_province_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='vtpost_district_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='vtpost_province_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='vtpost_ward_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
