# Generated by Django 4.2.3 on 2023-08-01 10:34
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations
from django.db import models

import promotions.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0003_alter_products_note_alter_productsvariants_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionVariant",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "PENDING"), ("in_progress", "IN_PROGRESS"), ("cancel", "CANCEL")],
                        default=promotions.enums.PromotionStatus["PENDING"],
                        max_length=11,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("price", "PRICE"), ("percent", "PERCENT"), ("other_variant", "OTHER_VARIANT")], max_length=13
                    ),
                ),
                ("giagiam_value", models.IntegerField(blank=True, null=True)),
                ("phantram_value", models.IntegerField(blank=True, null=True)),
                ("requirement_min_total_order_apply", models.IntegerField(blank=True, null=True)),
                ("requirement_max_total_quantity_variant", models.IntegerField(blank=True, null=True)),
                ("requirement_time_expire", models.DateTimeField(blank=True, null=True)),
                ("is_soft_delete", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_variant_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_variant_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_variant_promotion_variant",
                        to="products.productsvariants",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Promotions_Variants",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PromotionVoucher",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "PENDING"), ("in_progress", "IN_PROGRESS"), ("cancel", "CANCEL")],
                        default=promotions.enums.PromotionStatus["PENDING"],
                        max_length=11,
                    ),
                ),
                ("type", models.CharField(choices=[("price", "PRICE"), ("percent", "PERCENT")], max_length=11)),
                ("giagiam_value", models.IntegerField(blank=True, null=True)),
                ("phantram_value", models.IntegerField(blank=True, null=True)),
                ("requirement_min_total_order_apply", models.IntegerField(blank=True, null=True)),
                ("requirement_maximum_value_discount", models.IntegerField(blank=True, null=True)),
                ("requirement_number_used", models.IntegerField(blank=True, default=999999, null=True)),
                ("requirement_time_expire", models.DateTimeField(blank=True, null=True)),
                ("number_used", models.DateTimeField(blank=True, null=True)),
                ("is_soft_delete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_voucher_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_voucher_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Promotions_Vouchers",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PromotionVariantsOtherVariant",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("requirement_max_quantity", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_variants_other_variant_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_variants_other_variant_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotion_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_variant_other_variant",
                        to="promotions.promotionvariant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_variant_promotion_other_variant",
                        to="products.productsvariants",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Promotions_Variants_OtherVariant",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PromotionOrder",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "PENDING"), ("in_progress", "IN_PROGRESS"), ("cancel", "CANCEL")],
                        default=promotions.enums.PromotionStatus["PENDING"],
                        max_length=11,
                    ),
                ),
                ("type", models.CharField(choices=[("price", "PRICE"), ("percent", "PERCENT")], max_length=11)),
                ("giagiam_value", models.IntegerField(blank=True, null=True)),
                ("phantram_value", models.IntegerField(blank=True, null=True)),
                ("requirement_min_total_order_apply", models.IntegerField(blank=True, null=True)),
                ("requirement_maximum_value_discount", models.IntegerField(blank=True, null=True)),
                ("requirement_time_expire", models.DateTimeField(blank=True, null=True)),
                ("is_soft_delete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_order_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_order_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Promotions_Orders",
                "ordering": ["-created"],
            },
        ),
    ]
