# Generated by Django 5.0 on 2025-06-12 18:56

import django.utils.timezone
import model_utils.fields
import promotions.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionOrder',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_progress', 'IN_PROGRESS'), ('cancel', 'CANCEL')], default=promotions.enums.PromotionStatus['PENDING'], max_length=11)),
                ('type', models.CharField(choices=[('price', 'PRICE'), ('percent', 'PERCENT')], max_length=11)),
                ('price_value', models.IntegerField(blank=True, null=True)),
                ('percent_value', models.IntegerField(blank=True, null=True)),
                ('requirement_min_total_order_apply', models.IntegerField(blank=True, null=True)),
                ('requirement_maximum_value_discount', models.IntegerField(blank=True, null=True)),
                ('requirement_time_expire', models.DateTimeField(blank=True, null=True)),
                ('is_soft_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_Promotions_Orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromotionVariant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_progress', 'IN_PROGRESS'), ('cancel', 'CANCEL')], default=promotions.enums.PromotionStatus['PENDING'], max_length=11)),
                ('type', models.CharField(choices=[('price', 'PRICE'), ('percent', 'PERCENT'), ('other_variant', 'OTHER_VARIANT')], max_length=13)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_value', models.IntegerField(blank=True, null=True)),
                ('percent_value', models.IntegerField(blank=True, null=True)),
                ('requirement_min_total_quantity_variant_apply', models.IntegerField(blank=True, null=True)),
                ('requirement_max_total_quantity_variant', models.IntegerField(blank=True, null=True)),
                ('requirement_maximum_value_discount', models.IntegerField(blank=True, null=True)),
                ('requirement_time_expire', models.DateTimeField(blank=True, null=True)),
                ('is_soft_delete', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_Promotions_Variants',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromotionVariantsOtherVariant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('requirement_max_quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_Promotions_Variants_OtherVariant',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromotionVoucher',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_progress', 'IN_PROGRESS'), ('cancel', 'CANCEL')], default=promotions.enums.PromotionStatus['PENDING'], max_length=11)),
                ('type', models.CharField(choices=[('price', 'PRICE'), ('percent', 'PERCENT')], max_length=11)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('price_value', models.IntegerField(blank=True, null=True)),
                ('percent_value', models.IntegerField(blank=True, null=True)),
                ('requirement_min_total_order_apply', models.IntegerField(blank=True, null=True)),
                ('requirement_maximum_value_discount', models.IntegerField(blank=True, null=True)),
                ('requirement_number_used', models.IntegerField(blank=True, default=999999, null=True)),
                ('requirement_time_expire', models.DateTimeField(blank=True, null=True)),
                ('number_used', models.DateTimeField(blank=True, null=True)),
                ('is_soft_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_Promotions_Vouchers',
                'ordering': ['-created'],
            },
        ),
    ]
