# Generated by Django 4.2.3 on 2023-08-02 04:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotionvariant",
            old_name="requirement_min_total_order_apply",
            new_name="requirement_maximum_value_discount",
        ),
        migrations.AddField(
            model_name="promotionvariant",
            name="requirement_min_total_quantity_variant_apply",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
