# Generated by Django 5.0 on 2025-06-12 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_order_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionorder',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_order_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionvariant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_variant_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionvariant',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_variant_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionvariant',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant_promotion_variant', to='products.productsvariants'),
        ),
        migrations.AddField(
            model_name='promotionvariantsothervariant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_variants_other_variant_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionvariantsothervariant',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_variants_other_variant_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionvariantsothervariant',
            name='promotion_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_variant_other_variant', to='promotions.promotionvariant'),
        ),
        migrations.AddField(
            model_name='promotionvariantsothervariant',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant_promotion_other_variant', to='products.productsvariants'),
        ),
        migrations.AddField(
            model_name='promotionvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_voucher_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionvoucher',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_voucher_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
