# Generated by Django 4.2.4 on 2023-09-13 04:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_rename_requirement_min_total_order_apply_promotionvariant_requirement_maximum_value_discount_and_mor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotionorder",
            old_name="giagiam_value",
            new_name="price_value",
        ),
        migrations.RenameField(
            model_name="promotionvariant",
            old_name="giagiam_value",
            new_name="price_value",
        ),
        migrations.RenameField(
            model_name="promotionvoucher",
            old_name="giagiam_value",
            new_name="price_value",
        ),
        migrations.AddField(
            model_name="promotionorder",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="promotionorder",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionvariant",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="promotionvoucher",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="promotionvoucher",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
