# Generated by Django 4.2.4 on 2023-09-13 04:35
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0003_rename_giagiam_value_promotionorder_price_value_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotionorder",
            old_name="phantram_value",
            new_name="percent_value",
        ),
        migrations.RenameField(
            model_name="promotionvariant",
            old_name="phantram_value",
            new_name="percent_value",
        ),
        migrations.RenameField(
            model_name="promotionvoucher",
            old_name="phantram_value",
            new_name="percent_value",
        ),
    ]
