# Generated by Django 4.2.3 on 2023-08-04 02:54
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0007_alter_customeraddress_customer"),
        ("products", "0003_alter_products_note_alter_productsvariants_note"),
        ("leads", "0003_rename_landingpage_domain_historicallead_landing_page_domain_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotions", "0002_rename_requirement_min_total_order_apply_promotionvariant_requirement_maximum_value_discount_and_mor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order_number", models.PositiveBigIntegerField(editable=False)),
                ("order_key", models.CharField(editable=False, max_length=256)),
                ("sale_note", models.TextField(null=True)),
                ("delivery_note", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "COMPLETED"), ("cancel", "CANCEL"), ("draft", "DRAFT")], default="draft", max_length=9
                    ),
                ),
                ("phone_shipping", models.CharField(max_length=15)),
                ("name_shipping", models.CharField(max_length=255)),
                ("is_print", models.BooleanField(default=False)),
                ("printed_at", models.DateTimeField(null=True)),
                ("third_party_id", models.CharField(max_length=255, null=True)),
                ("third_party_name", models.CharField(max_length=255, null=True)),
                ("third_party_type", models.CharField(max_length=255, null=True)),
                ("is_cross_sale", models.BooleanField(default=False)),
                ("value_cross_sale", models.PositiveBigIntegerField(default=0)),
                ("appointment_date", models.DateTimeField(null=True)),
                ("quatity_total_variant_all", models.PositiveIntegerField(default=0)),
                ("price_total_variant_all", models.PositiveBigIntegerField(default=0)),
                ("price_total_variant_actual", models.PositiveBigIntegerField(default=0)),
                ("price_total_discount_order_promotion", models.PositiveBigIntegerField(default=0)),
                ("price_discount_input", models.PositiveBigIntegerField(default=0)),
                ("price_addition_input", models.PositiveBigIntegerField(default=0)),
                ("price_total_order_actual", models.PositiveBigIntegerField(default=0)),
                ("price_pre_paid", models.PositiveBigIntegerField(default=0)),
                ("price_after_paid", models.PositiveBigIntegerField(default=0)),
                ("complete_time", models.DateTimeField(null=True)),
                ("tracking_number", models.CharField(max_length=255, null=True)),
                (
                    "address_shipping",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="customers.customeraddress"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Orders",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OrdersCancelReason",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "tbl_Orders_Cancel_Reason",
            },
        ),
        migrations.CreateModel(
            name="OrdersItems",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("price_variant_logs", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField(default=0)),
                ("price_total", models.PositiveBigIntegerField()),
                ("third_party_item_id", models.CharField(max_length=255, null=True)),
                ("third_party_source", models.CharField(max_length=255, null=True)),
                ("is_cross_sale", models.BooleanField(default=False)),
                (
                    "type_data_flow",
                    models.CharField(
                        choices=[("SIMPLE", "SIMPLE"), ("COMBO", "COMBO"), ("PROMOTION", "PROMOTION")], default="SIMPLE", max_length=13
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="orders.orders")),
                (
                    "variant",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_items", to="products.productsvariants"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Orders_Items",
            },
        ),
        migrations.CreateModel(
            name="OrdersTag",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "tbl_Orders_Tags",
            },
        ),
        migrations.CreateModel(
            name="OrderVariantsPromotion",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("price", models.PositiveBigIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_variant_promotions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_promotions_used",
                        to="orders.ordersitems",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_variant_promotions_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotion_variant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_variants",
                        to="promotions.promotionvariant",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Order_Variants_Promotion",
            },
        ),
        migrations.CreateModel(
            name="OrdersItemsPromotion",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveSmallIntegerField(default=0)),
                ("price", models.PositiveBigIntegerField()),
                ("total", models.PositiveBigIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_promotion_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_promotion_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_variant_promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items_promotion", to="orders.ordervariantspromotion"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="line_items_promotions",
                        to="products.productsvariants",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Orders_Items_Promotion",
            },
        ),
        migrations.CreateModel(
            name="OrdersItemsCombo",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("price", models.PositiveBigIntegerField()),
                ("total", models.PositiveBigIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_combo_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line_item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items_combo", to="orders.ordersitems"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_combo_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_combos",
                        to="products.productsvariants",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Orders_Items_Combo",
            },
        ),
        migrations.AddField(
            model_name="orders",
            name="cancel_reason",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="orders.orderscancelreason"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_created", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="customer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="modified_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_modified", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="printed_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_printed", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="source",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rders", to="leads.leadchannel"),
        ),
        migrations.AddField(
            model_name="orders",
            name="tags",
            field=models.ManyToManyField(blank=True, db_table="tbl_Orders_Tags_Detail", to="orders.orderstag"),
        ),
        migrations.CreateModel(
            name="HistoricalOrdersPayments",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("COD", "COD"), ("DIRECT_TRANSFER", "DIRECT_TRANSFER"), ("CASH", "CASH")], default="COD", max_length=15
                    ),
                ),
                ("price_from_order", models.PositiveBigIntegerField(null=True)),
                ("price_from_third_party", models.PositiveBigIntegerField(null=True)),
                ("date_from_third_party", models.DateTimeField(null=True)),
                ("price_from_upload_file", models.PositiveBigIntegerField(null=True)),
                ("date_from_upload_file", models.DateTimeField(null=True)),
                ("is_confirm", models.BooleanField(default=False)),
                ("date_confirm", models.DateTimeField(null=True)),
                ("note", models.TextField(null=True)),
                ("image", models.URLField(null=True)),
                ("history_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.orders",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical orders payments",
                "verbose_name_plural": "historical orders paymentss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrders",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("order_number", models.PositiveBigIntegerField(editable=False)),
                ("order_key", models.CharField(editable=False, max_length=256)),
                ("sale_note", models.TextField(null=True)),
                ("delivery_note", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "COMPLETED"), ("cancel", "CANCEL"), ("draft", "DRAFT")], default="draft", max_length=9
                    ),
                ),
                ("phone_shipping", models.CharField(max_length=15)),
                ("name_shipping", models.CharField(max_length=255)),
                ("is_print", models.BooleanField(default=False)),
                ("printed_at", models.DateTimeField(null=True)),
                ("third_party_id", models.CharField(max_length=255, null=True)),
                ("third_party_name", models.CharField(max_length=255, null=True)),
                ("third_party_type", models.CharField(max_length=255, null=True)),
                ("is_cross_sale", models.BooleanField(default=False)),
                ("value_cross_sale", models.PositiveBigIntegerField(default=0)),
                ("appointment_date", models.DateTimeField(null=True)),
                ("quatity_total_variant_all", models.PositiveIntegerField(default=0)),
                ("price_total_variant_all", models.PositiveBigIntegerField(default=0)),
                ("price_total_variant_actual", models.PositiveBigIntegerField(default=0)),
                ("price_total_discount_order_promotion", models.PositiveBigIntegerField(default=0)),
                ("price_discount_input", models.PositiveBigIntegerField(default=0)),
                ("price_addition_input", models.PositiveBigIntegerField(default=0)),
                ("price_total_order_actual", models.PositiveBigIntegerField(default=0)),
                ("price_pre_paid", models.PositiveBigIntegerField(default=0)),
                ("price_after_paid", models.PositiveBigIntegerField(default=0)),
                ("complete_time", models.DateTimeField(null=True)),
                ("tracking_number", models.CharField(max_length=255, null=True)),
                ("history_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "address_shipping",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="customers.customeraddress",
                    ),
                ),
                (
                    "cancel_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.orderscancelreason",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="customers.customer",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical orders",
                "verbose_name_plural": "historical orderss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OrdersPromotion",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("price", models.PositiveBigIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_promotions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_promotions_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promotions_used", to="orders.orders"),
                ),
                (
                    "promotion_order",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_used", to="promotions.promotionorder"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Orders_Promotion",
                "unique_together": {("order", "promotion_order")},
            },
        ),
        migrations.CreateModel(
            name="OrdersPayments",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("COD", "COD"), ("DIRECT_TRANSFER", "DIRECT_TRANSFER"), ("CASH", "CASH")], default="COD", max_length=15
                    ),
                ),
                ("price_from_order", models.PositiveBigIntegerField(null=True)),
                ("price_from_third_party", models.PositiveBigIntegerField(null=True)),
                ("date_from_third_party", models.DateTimeField(null=True)),
                ("price_from_upload_file", models.PositiveBigIntegerField(null=True)),
                ("date_from_upload_file", models.DateTimeField(null=True)),
                ("is_confirm", models.BooleanField(default=False)),
                ("date_confirm", models.DateTimeField(null=True)),
                ("note", models.TextField(null=True)),
                ("image", models.URLField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="orders.orders")),
            ],
            options={
                "db_table": "tbl_Orders_Payments",
                "ordering": ["-created"],
                "unique_together": {("order", "type")},
            },
        ),
    ]
