# Generated by Django 5.0 on 2025-06-12 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('leads', '0002_initial'),
        ('locations', '0002_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationsheetlog',
            name='scan_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_confirm_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='address_shipping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.address'),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='complete_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='printed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.leadchannel'),
        ),
        migrations.AddField(
            model_name='historicalorderspayments',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorderspayments',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='assign_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='handle_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='address_shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='locations.address'),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_complete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='printed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_printed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='leads.leadchannel'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancel_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.orderscancelreason'),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orderscancelreason'),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_items', to='products.productsvariants'),
        ),
        migrations.AddField(
            model_name='ordersitemscombo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_combo_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersitemscombo',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_combo', to='orders.ordersitems'),
        ),
        migrations.AddField(
            model_name='ordersitemscombo',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_combo_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersitemscombo',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_combos', to='products.productsvariants'),
        ),
        migrations.AddField(
            model_name='ordersitemspromotion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_promotion_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersitemspromotion',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_promotion_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersitemspromotion',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items_promotions', to='products.productsvariants'),
        ),
        migrations.AddField(
            model_name='orderspayments',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderspayments',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderspayments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orderspromotion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_promotions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderspromotion',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_promotions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderspromotion',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_used', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orderspromotion',
            name='promotion_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_used', to='promotions.promotionorder'),
        ),
        migrations.AddField(
            model_name='orders',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='tbl_Orders_Tags_Detail', to='orders.orderstag'),
        ),
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.orderstype'),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orderstype'),
        ),
        migrations.AddField(
            model_name='ordervariantspromotion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_variant_promotions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordervariantspromotion',
            name='line_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_promotions_used', to='orders.ordersitems'),
        ),
        migrations.AddField(
            model_name='ordervariantspromotion',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_variant_promotions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordervariantspromotion',
            name='promotion_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_variants', to='promotions.promotionvariant'),
        ),
        migrations.AddField(
            model_name='ordersitemspromotion',
            name='order_variant_promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_promotion', to='orders.ordervariantspromotion'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='assign_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_care_assign_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='handle_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_care_handle_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_care_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_care', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='action_old',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_care_action', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='late_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_late_action', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='returned_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_returned_action', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='returning_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_wait_returning_action', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='wait_return_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_wait_return_action', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='action_old',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='late_action',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='returned_action',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='returning_action',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='wait_return_action',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcareaction'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='late_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_late_reason', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='reason_old',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_care_reason', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='returned_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_returned_reason', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='returning_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_wait_returning_reason', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='transportationcare',
            name='wait_return_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_wait_return_reason', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='late_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='reason_old',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='returned_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='returning_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcarereason'),
        ),
        migrations.AddField(
            model_name='historicaltransportationcare',
            name='wait_return_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.transportationcarereason'),
        ),
        migrations.AlterUniqueTogether(
            name='orderspayments',
            unique_together={('order', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='orderspromotion',
            unique_together={('order', 'promotion_order')},
        ),
    ]
