# Generated by Django 4.2.3 on 2023-08-04 03:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorders",
            name="order_key",
            field=models.CharField(db_index=True, editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalorders",
            name="order_number",
            field=models.PositiveBigIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_key",
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.PositiveBigIntegerField(editable=False, unique=True),
        ),
    ]
