# Generated by Django 4.2.3 on 2023-08-04 07:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_historicalorders_order_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordervariantspromotion",
            name="line_item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="variant_promotions_used", to="orders.ordersitems"
            ),
        ),
    ]
