# Generated by Django 4.2.5 on 2023-09-15 06:33
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_alter_historicallead_call_handle_number_and_more"),
        ("orders", "0003_alter_ordervariantspromotion_line_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={"ordering": ["-order_key"]},
        ),
        migrations.AlterModelOptions(
            name="orderscancelreason",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="orderstag",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="historicalorders",
            name="price_delivery_input",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orders",
            name="price_delivery_input",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orders",
            name="source",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="leads.leadchannel"),
        ),
    ]
