# Generated by Django 4.2.5 on 2023-09-18 06:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_address_address_unique_customer_address"),
        ("orders", "0004_alter_orders_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorders",
            name="address_shipping",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.address",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="address_shipping",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="locations.address"),
        ),
    ]
