# Generated by Django 4.2.5 on 2023-10-03 07:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_historicalorders_address_shipping_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorders",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="order_key",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="order_number",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_addition_input",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_after_paid",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_delivery_input",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_discount_input",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_pre_paid",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_total_discount_order_promotion",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_total_order_actual",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_total_variant_actual",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="price_total_variant_all",
        ),
        migrations.RemoveField(
            model_name="historicalorders",
            name="quatity_total_variant_all",
        ),
        migrations.AlterModelTable(
            name="historicalorders",
            table="tbl_Orders_Historical",
        ),
    ]
