# Generated by Django 4.2.5 on 2023-10-04 02:24
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_historicalorders_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorderspayments",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalorderspayments",
            name="order",
        ),
        migrations.RemoveField(
            model_name="historicalorderspayments",
            name="price_from_order",
        ),
        migrations.AlterModelTable(
            name="historicalorderspayments",
            table="tbl_Orders_Payments_Historical",
        ),
    ]
