# Generated by Django 4.2.5 on 2023-10-04 02:49
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_historicalorderspayments_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorderspayments",
            name="created",
        ),
    ]
