# Generated by Django 4.2.5 on 2023-10-10 04:39
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_historicalorderspayments_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorderspayments",
            name="image",
        ),
        migrations.RemoveField(
            model_name="orderspayments",
            name="image",
        ),
    ]
