# Generated by Django 4.2.5 on 2023-10-23 03:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_historicalorderspayments_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordersitems",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="ordersitemscombo",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="ordersitemspromotion",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="orderspromotion",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="ordervariantspromotion",
            options={"ordering": ["-created"]},
        ),
    ]
