# Generated by Django 4.2.5 on 2023-11-20 08:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_ordersitems_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorders",
            name="price_total_variant_all_neo",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="price_total_variant_all_neo",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ordersitems",
            name="price_total_neo",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="price_addition_input",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orders",
            name="price_delivery_input",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orders",
            name="price_discount_input",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orders",
            name="quatity_total_variant_all",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
