# Generated by Django 4.2.5 on 2023-11-21 09:37
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0011_historicalorders_price_total_variant_all_neo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorders",
            name="complete_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="complete_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_complete", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
