# Generated by Django 4.2.5 on 2023-12-26 04:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_historicalorders_complete_by_orders_complete_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersitems",
            name="is_promo_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordersitems",
            name="sales_bonus",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
