# Generated by Django 4.2.9 on 2024-01-12 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_ordersitems_is_promo_sale_ordersitems_sales_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationSheetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.IntegerField()),
                ('order_number', models.PositiveBigIntegerField(null=True)),
                ('order_key', models.CharField(max_length=256)),
                ('scan_at', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True)),
                ('log_message', models.TextField(blank=True, max_length=512)),
                ('type', models.CharField(choices=[('IP', 'Import'), ('EP', 'Export')], max_length=36, null=True)),
                ('scan_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_confirm_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
