# Generated by Django 4.2.7 on 2024-03-12 03:26
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_confirmationsheetlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersPaymentsNotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
