# Generated by Django 5.0 on 2024-03-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderspaymentsnotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdersPaymentsNotion',
        ),
    ]
