# Generated by Django 5.0 on 2024-03-14 10:54
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_delete_orderspaymentsnotion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportationCareAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, max_length=264, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("late", "LATE"), ("wait_return", "WAIT_RETURN"), ("returning", "RETURNING"), ("returned", "RETURNED")],
                        max_length=18,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportationCareReason",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, max_length=264, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("late", "LATE"), ("wait_return", "WAIT_RETURN"), ("returning", "RETURNING"), ("returned", "RETURNED")],
                        max_length=18,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportationCare",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("appointment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("pending", "PENDING"),
                            ("processing", "PROCESSING"),
                            ("handled", "HANDLED"),
                            ("completed", "COMPLETED"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("late_created", models.DateTimeField(blank=True, null=True)),
                ("wait_return_created", models.DateTimeField(blank=True, null=True)),
                ("returning_created", models.DateTimeField(blank=True, null=True)),
                ("returned_created", models.DateTimeField(blank=True, null=True)),
                (
                    "created_reason_old",
                    models.CharField(
                        blank=True,
                        choices=[("late", "LATE"), ("wait_return", "WAIT_RETURN"), ("returning", "RETURNING"), ("returned", "RETURNED")],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "assign_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_care_assign_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handle_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_care_handle_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_care_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transportation_care", to="orders.orders"
                    ),
                ),
                (
                    "action_old",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_care_action",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "late_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_late_action",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "returned_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_returned_action",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "returning_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_wait_returning_action",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "wait_return_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_wait_return_action",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "late_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_late_reason",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "reason_old",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_care_reason",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "returned_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_returned_reason",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "returning_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_wait_returning_reason",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "wait_return_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportation_wait_return_reason",
                        to="orders.transportationcarereason",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
