# Generated by Django 5.0 on 2024-03-15 03:13
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_transportationcareaction_transportationcarereason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transportationcare",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelTable(
            name="transportationcare",
            table="tbl_Transportation_Care",
        ),
        migrations.AlterModelTable(
            name="transportationcareaction",
            table="tbl_Transportation_Care_Action",
        ),
        migrations.AlterModelTable(
            name="transportationcarereason",
            table="tbl_Transportation_Care_Reason",
        ),
        migrations.CreateModel(
            name="HistoricalTransportationCare",
            fields=[
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("appointment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("pending", "PENDING"),
                            ("processing", "PROCESSING"),
                            ("handled", "HANDLED"),
                            ("completed", "COMPLETED"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("late_created", models.DateTimeField(blank=True, null=True)),
                ("wait_return_created", models.DateTimeField(blank=True, null=True)),
                ("returning_created", models.DateTimeField(blank=True, null=True)),
                ("returned_created", models.DateTimeField(blank=True, null=True)),
                (
                    "created_reason_old",
                    models.CharField(
                        blank=True,
                        choices=[("late", "LATE"), ("wait_return", "WAIT_RETURN"), ("returning", "RETURNING"), ("returned", "RETURNED")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("history_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "action_old",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "assign_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handle_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "late_action",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "late_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.orders",
                    ),
                ),
                (
                    "reason_old",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "returned_action",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "returned_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "returning_action",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "returning_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcarereason",
                    ),
                ),
                (
                    "wait_return_action",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcareaction",
                    ),
                ),
                (
                    "wait_return_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.transportationcarereason",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical transportation care",
                "verbose_name_plural": "historical transportation cares",
                "db_table": "tbl_tbl_Transportation_Care_Historical",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
