# Generated by Django 5.0 on 2024-03-15 03:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_alter_transportationcare_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historicaltransportationcare",
            table="tbl_Transportation_Care_Historical",
        ),
    ]
