# Generated by Django 5.0 on 2024-03-15 07:30
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_alter_historicaltransportationcare_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transportationcareaction",
            old_name="type",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="transportationcarereason",
            old_name="type",
            new_name="name",
        ),
    ]
