# Generated by Django 5.0 on 2024-03-15 07:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_rename_type_transportationcareaction_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportationcareaction",
            name="label",
        ),
        migrations.RemoveField(
            model_name="transportationcarereason",
            name="label",
        ),
        migrations.AddField(
            model_name="transportationcareaction",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("late", "LATE"), ("wait_return", "WAIT_RETURN"), ("returning", "RETURNING"), ("returned", "RETURNED")],
                max_length=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transportationcarereason",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("late", "LATE"), ("wait_return", "WAIT_RETURN"), ("returning", "RETURNING"), ("returned", "RETURNED")],
                max_length=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transportationcareaction",
            name="name",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name="transportationcarereason",
            name="name",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
