# Generated by Django 5.0 on 2024-06-05 06:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_remove_transportationcareaction_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorders",
            name="name_shipping",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorders",
            name="phone_shipping",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="name_shipping",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="phone_shipping",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
