# Generated by Django 5.0 on 2024-06-05 07:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_alter_historicalorders_name_shipping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersitems",
            name="price_variant_logs",
            field=models.PositiveBigIntegerField(),
        ),
    ]
