# Generated by Django 5.0 on 2024-07-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_ordersitems_price_variant_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price_total_variant_actual_input',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='price_total_input',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
