# Generated by Django 5.0 on 2024-07-22 06:13
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_orders_price_total_variant_actual_input_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="quatity_total_variant_all",
        ),
    ]
