# Generated by Django 5.0 on 2025-04-21 02:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_orders_quatity_total_variant_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationcare',
            name='action_old',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='assign_by',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='handle_by',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='late_action',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='late_reason',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='reason_old',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='returned_action',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='returned_reason',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='returning_action',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='returning_reason',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='wait_return_action',
        ),
        migrations.RemoveField(
            model_name='transportationcare',
            name='wait_return_reason',
        ),
        migrations.DeleteModel(
            name='HistoricalTransportationCare',
        ),
        migrations.DeleteModel(
            name='TransportationCareAction',
        ),
        migrations.DeleteModel(
            name='TransportationCare',
        ),
        migrations.DeleteModel(
            name='TransportationCareReason',
        ),
    ]
