# Generated by Django 4.2.5 on 2023-09-18 10:28
import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations
from django.db import models

import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_alter_products_note_alter_productsvariants_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified"),
                ),
                ("id", model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("PD", "PRODUCT"), ("US", "USER"), ("OT", "OTHER")], default=files.models.ImageTypes["OTHER"], max_length=2
                    ),
                ),
                ("image", models.ImageField(upload_to=files.models.image_file_path)),
                (
                    "product",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.products"
                    ),
                ),
                (
                    "upload_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="images_uploaded", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="images", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "tbl_Images",
                "ordering": ["-created"],
            },
        ),
    ]
