# Generated by Django 5.0 on 2025-06-12 18:56

import django.utils.timezone
import files.models
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PD', 'PRODUCT'), ('PDV', 'PRODUCT_VARIANT'), ('US', 'USER'), ('PM', 'PAYMENT'), ('OT', 'OTHER'), ('MT', 'MATERIAL'), ('OD', 'ORDER')], default=files.models.ImageTypes['OTHER'], max_length=5)),
                ('image', models.ImageField(upload_to=files.models.image_file_path)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_Images',
                'ordering': ['-created'],
            },
        ),
    ]
