# Generated by Django 4.2.5 on 2023-09-19 03:09
import django.db.models.deletion
from django.db import migrations
from django.db import models

import files.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_products_note_alter_productsvariants_note"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="product_variant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.productsvariants"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="type",
            field=models.CharField(
                choices=[("PD", "PRODUCT"), ("PDV", "PRODUCT_VARIANT"), ("US", "USER"), ("OT", "OTHER")],
                default=files.models.ImageTypes["OTHER"],
                max_length=5,
            ),
        ),
    ]
