# Generated by Django 4.2.5 on 2023-10-10 02:51
import django.db.models.deletion
from django.db import migrations
from django.db import models

import files.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_historicalorderspayments_created"),
        ("files", "0002_images_product_variant_alter_images_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="payment",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="images", to="orders.orderspayments"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="type",
            field=models.CharField(
                choices=[("PD", "PRODUCT"), ("PDV", "PRODUCT_VARIANT"), ("US", "USER"), ("PM", "PAYMENT"), ("OT", "OTHER")],
                default=files.models.ImageTypes["OTHER"],
                max_length=5,
            ),
        ),
    ]
