# Generated by Django 5.0 on 2024-07-12 06:50
import django.db.models.deletion
from django.db import migrations
from django.db import models

import files.models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_images_payment_alter_images_type"),
        ("products", "0008_productsvariantsbatches_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="material",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.productsmaterials"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="type",
            field=models.CharField(
                choices=[
                    ("PD", "PRODUCT"),
                    ("PDV", "PRODUCT_VARIANT"),
                    ("US", "USER"),
                    ("PM", "PAYMENT"),
                    ("OT", "OTHER"),
                    ("MT", "MATERITAL"),
                ],
                default=files.models.ImageTypes["OTHER"],
                max_length=5,
            ),
        ),
    ]
