# Generated by Django 5.0 on 2024-09-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_images_material_alter_images_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
