# Generated by Django 5.0 on 2024-11-01 08:06

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_images_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='type',
            field=models.CharField(choices=[('PD', 'PRODUCT'), ('PDV', 'PRODUCT_VARIANT'), ('US', 'USER'), ('PM', 'PAYMENT'), ('OT', 'OTHER'), ('MT', 'MATERIAL')], default=files.models.ImageTypes['OTHER'], max_length=5),
        ),
    ]
